const uiTexts = {
	fr: {
		myNotes: "Mes notes",
		exportNotes: "Exporter",
		hideNotes: "Cacher les notes",
		enterNote: "Entrer votre note",
		addNote: "Ajouter",
		editNote: "Éditer",
		deleteNote: "Supprimer",
		updateNote: "Modifier",
		alertNoNote: "Merci d'entrer une note",
		alertNoNotesToExport: "Pas de notes à exporter!",
		hideInterface: "Masquer l'interface",
		showInterface: "Afficher l'interface",
		previousPage: "Page précédente",
		nextPage: "Page suivante",
		localPDF: "PDF en local",
		onlinePDF: "PDF en ligne",
		enterPDFurl: "Entrer l'URL de votre PDF",
		selectPDF: "Sélectionner un PDF",
		loadPDF: "Charger le PDF",
		loadingPDF: "Chargement du PDF",
		loadingOf: "Chargement du",
		foldSelectPDFmenu: "Replier ce menu",
		zoomIn: "Zoomer",
		zoomOut: "Dézoomer",
		useFullScreen: "Plein écran ?",
		print: "Imprimer",
		Share: "Partager",
		info: "Plus d'informations sur PDF2flip",
		alertNoValidURL: "L'URL de votre fichier ne semble pas valide",
		alertNoValidFile: "Pas de PDF valide",
		cancel: "Annuler",
		confirmCopyToClipboard:
			"Votre lien a été copié dans le presse-papier. Cliquez sur “OK” pour que ce lien affiche seulement le flipbook sans l'interface.",
		errorWithCopyToClipboard: "Erreur lors de la copie du lien : ",
	},
	en: {
		myNotes: "My Notes",
		exportNotes: "Export",
		hideNotes: "Hide notes",
		enterNote: "Enter your note",
		addNote: "Add",
		editNote: "Edit",
		deleteNote: "Delete",
		updateNote: "Update",
		alertNoNote: "Please enter a note",
		alertNoNotesToExport: "No notes to export!",
		hideInterface: "Hide interface",
		showInterface: "Show interface",
		previousPage: "Previous page",
		nextPage: "Next page",
		localPDF: "Local PDF",
		onlinePDF: "Online PDF",
		enterPDFurl: "Enter your PDF URL",
		selectPDF: "Select a PDF",
		loadPDF: "Load PDF",
		loadingPDF: "Loading PDF",
		loadingOf: "Loading of",
		foldSelectPDFmenu: "Collapse this menu",
		zoomIn: "Zoom in",
		zoomOut: "Zoom out",
		useFullScreen: "Fullscreen?",
		print: "Print",
		share: "Share",
		info: "More information about PDF2flip",
		alertNoValidURL: "The URL of your file does not seem to be valid",
		alertNoValidFile: "No valid PDF",
		cancel: "Cancel",
		confirmCopyToClipboard:
			"Your link has been copied to the clipboard. Click on ‘OK’ so that this link only displays the flipbook without the interface.",
		errorWithCopyToClipboard: "Error copying link : ",
	},
};
