const uiTexts = {
	fr: {
		myNotes: "Mes notes",
		exportNotes: "Exporter",
		hideNotes: "Cacher les notes",
		writeNote: "Écrire une note",
		addNote: "Ajouter",
		editNote: "Éditer",
		deleteNote: "Supprimer",
		updateNote: "Modifier",
		alertNoNote: "Merci d'écrire une note",
		alertNoNotesToExport: "Pas de notes à exporter!",
		hideInterface: "Masquer l'interface",
		showInterface: "Afficher l'interface",
		previousPage: "Page précédente",
		nextPage: "Page suivante",
		localPDF: "PDF en local",
		onlinePDF: "PDF en ligne",
		enterPDFurl: "Entrer l'URL de votre PDF",
		selectPDF: "Sélectionner un PDF",
		loadPDF: "Charger le PDF",
		loadingPDF: "Chargement du PDF",
		loadingOf: "Chargement du",
		downloadPDF: "Télécharger le PDF",
		foldSelectPDFmenu: "Replier ce menu",
		zoomIn: "Zoomer",
		zoomOut: "Dézoomer",
		useFullScreen: "Plein écran ?",
		print: "Imprimer",
		share: "Partager",
		info: "Plus d'informations sur PDF2flip",
		alertNoValidURL:
			"Accès impossible : pdf2flip ne peut pas visualiser le fichier. Souhaitez-vous l'ouvrir pour pouvoir le télécharger ?",
		alertNoValidFile: "Pas de PDF valide",
		cancel: "Annuler",
		confirmCopyToClipboard:
			"Votre lien a été copié dans le presse-papier. Cliquez sur “OK” pour que ce lien affiche seulement le flipbook sans l'interface.",
		errorWithCopyToClipboard: "Erreur lors de la copie du lien : ",
	},
	en: {
		myNotes: "My Notes",
		exportNotes: "Export",
		hideNotes: "Hide notes",
		writeNote: "Write your note",
		addNote: "Add",
		editNote: "Edit",
		deleteNote: "Delete",
		updateNote: "Update",
		alertNoNote: "Please write a note",
		alertNoNotesToExport: "No notes to export!",
		hideInterface: "Hide interface",
		showInterface: "Show interface",
		previousPage: "Previous page",
		nextPage: "Next page",
		localPDF: "Local PDF",
		onlinePDF: "Online PDF",
		enterPDFurl: "Enter your PDF URL",
		selectPDF: "Select a PDF",
		loadPDF: "Load PDF",
		loadingPDF: "Loading PDF",
		loadingOf: "Loading of",
		downloadPDF: "Download PDF",
		foldSelectPDFmenu: "Collapse this menu",
		zoomIn: "Zoom in",
		zoomOut: "Zoom out",
		useFullScreen: "Fullscreen?",
		print: "Print",
		share: "Share",
		info: "More information about PDF2flip",
		alertNoValidURL:
			"Unable to access: pdf2flip cannot view the file. Would you like to open it and download it?",
		alertNoValidFile: "No valid PDF",
		cancel: "Cancel",
		confirmCopyToClipboard:
			"Your link has been copied to the clipboard. Click on ‘OK’ so that this link only displays the flipbook without the interface.",
		errorWithCopyToClipboard: "Error copying link : ",
	},
	oc: {
		myNotes: "Mas nòtas",
		exportNotes: "Exportar",
		hideNotes: "Amagar las nòtas",
		writeNote: "Escriure una nòta",
		addNote: "Apondre",
		editNote: "Editar",
		deleteNote: "Suprimir",
		updateNote: "Modificar",
		alertNoNote: "Mercé d'escriure una nòta",
		alertNoNotesToExport: "Cap de nòta a exportar !",
		hideInterface: "Amagar l'interfàcia",
		showInterface: "Mostrar l'interfàcia",
		previousPage: "Pagina precedenta",
		nextPage: "Pagina seguenta",
		localPDF: "PDF en local",
		onlinePDF: "PDF en linha",
		enterPDFurl: "Picar l'URL del PDF",
		selectPDF: "Seleccionar un PDF",
		loadPDF: "Cargar lo PDF",
		loadingPDF: "Cargament del PDF",
		loadingOf: "Cargament del",
		downloadPDF: "Telecargar lo PDF",
		foldSelectPDFmenu: "Replegar aqueste menut",
		zoomIn: "Agrandir",
		zoomOut: "Reduire",
		useFullScreen: "Plen ecran ?",
		print: "Imprimir",
		share: "Partejar",
		info: "Mai d'informacions a prepaus de PDF2flip",
		alertNoValidURL:
			"Impossible d'i accedir : pdf2flip pòt pas visualizar lo fichièr. O volètz dobrir per que lo poscatz telecargar?",
		alertNoValidFile: "Cap de PDF pas valide",
		cancel: "Anullar",
		confirmCopyToClipboard:
			"Vòstre ligam es estat copiat al quichapapièrs. Clicatz “OK” per que lo ligam mòstre pas que lo flipbook sens l'interfàcia.",
		errorWithCopyToClipboard: "Error pendent la còpia del ligam : ",
	},
};
